MyStory/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration;
using System.Web.Mvc;

namespace MyStory.Models
{
    public class Post
    {
        public Post()
        {
            this.Tags = new List<Tag>();
            this.Comments = new List<Comment>();
        }
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
        public Location LocationOfWriting { get; set; }
        public int BlogId { get; set; }
        public virtual Blog Blog { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }

    public class PostMap : EntityTypeConfiguration<Post>
    {
        public PostMap()
        {
            // Table
            this.ToTable("Posts");

            // Properties
            this.Property(p => p.Title)
                .IsRequired()
                .HasMaxLength(125);

            this.Property(p => p.Content)
                .IsRequired();

            this.Property(p => p.DateCreated)
                .IsRequired();

            // Relationships
            this.HasMany(p => p.Tags)
                .WithMany(t => t.Posts)
                .Map
                (
                    m =>
                    {
                        m.MapLeftKey("PostId");
                        m.MapRightKey("TagId");
                        m.ToTable("TagPost");
                    }
                );

        }
    }

}

MyStory/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStory.ViewModels;
using MyStory.Models;
using AutoMapper;

namespace MyStory.Controllers
{
    public class CommentController : MyStoryController
    {
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            var recentComments = DbContext.Comments.OrderByDescending(c => c.DateCreated).Take(10).ToList();
            var recentCommentsViewModel = Mapper.Map<List<Comment>, List<CommentSidebarViewModel>>(recentComments);
            recentCommentsViewModel.ForEach(c =>
            {
                if (c.Content.Length > 50)
                    c.Content = c.Content.Substring(0, 50);
            });

            return View("Sidebar", recentCommentsViewModel);
        }

        public ActionResult PostCommentsList(int? postId)
        {
            if (postId == null)
                return View("PostCommentsList");

            var comments = DbContext.Comments.Where(c => c.PostId == postId).OrderBy(c=>c.DateCreated);

            var postCommentsViewModel = new PostCommentsViewModel();
            postCommentsViewModel.PostId = postId.Value;
            //TODO use automapper instead of manual mapping
            foreach (var comment in comments)
            {
                var commentSummary = new MyStory.ViewModels.PostCommentsViewModel.CommentSummary 
                { 
                    CommenterEmail = comment.Commenter.Email,
                    CommenterName = comment.Commenter.Name,
                    CommenterOpenId = comment.Commenter.OpenId,
                    CommenterUrl = comment.Commenter.Url,
                    Content = comment.Content,
                    DateCreated = comment.DateCreated,
                    Id = comment.Id
                };
                
                postCommentsViewModel.Comments.Add(commentSummary);
            }

            return View("PostCommentsList", postCommentsViewModel);
        }

        [HttpPost]
        public ActionResult Write([Bind(Prefix="CommentInput")] CommentInput input, int id)
        {
            if (!ModelState.IsValid)
            {
                var errors = (from item in ModelState
                              where item.Value.Errors.Any()
                              select new { ErrorKey = item.Key, ErrorMessage = item.Value.Errors.FirstOrDefault().ErrorMessage }).ToDictionary(a => a.ErrorKey, a=>a.ErrorMessage);
                TempData["commentInputData"] = input;
                TempData["commentInputDataErrors"] = errors;
                return RedirectToAction("Detail", "Post", new { id = id, errorFromCommentInput = true });
            }

            // TODO handle commenter info when info in db is different from info from ui
            var commenter = DbContext.Commenters.SingleOrDefault(c => c.Email == input.Email) ?? GetCommenter(input);

            DbContext.Comments.Add(new Comment
            {
                PostId = id,
                Content = input.Content,
                DateCreated = DateTime.Now,
                Commenter = commenter
            });

            DbContext.SaveChanges();

            return RedirectToAction("Detail", "Post", new { id = id });
        }

        private Commenter GetCommenter(CommentInput input)
        {
            if (!string.IsNullOrWhiteSpace(input.OpenId) && DbContext.Commenters.Count(c => c.OpenId == input.OpenId) > 0)
            {
                // this means that user changed email and user name in comment input form that has a openid value as hidden field
                // that is, user does not want use openid, so that openid will not be saved
                return new Commenter
                {
                    Email = input.Email,
                    Name = input.Name,
                    Url = input.Url
                };
            }
            else
            {
                return new Commenter
                {
                    Email = input.Email,
                    Name = input.Name,
                    OpenId = input.OpenId,
                    Url = input.Url
                };
            }
        }

        

    }
}

MyStory/Controllers/OpenIdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetOpenAuth.OpenId.RelyingParty;
using DotNetOpenAuth.OpenId;
using DotNetOpenAuth.OpenId.Extensions.AttributeExchange;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OpenId.Extensions.SimpleRegistration;
using MyStory.Infrastructure.Common;
using MyStory.Models;

namespace MyStory.Controllers
{
    public class OpenIdController : MyStoryController
    {
        private static readonly OpenIdRelyingParty Openid = new OpenIdRelyingParty();

        [ValidateInput(false)]
        public ActionResult Authenticate(string returnUrl)
        {
            var response = Openid.GetResponse();
            if (response == null)
            {
                Identifier id;
                //make sure users openid_identifier is valid.
                if (Identifier.TryParse(Request.Form["openid_identifier"], out id))
                {
                    try
                    {
                        var uri = new UriBuilder(Url.RouteUrl("default", null, "http"))
                        {
                            Query = string.Format("returnUrl={0}", Uri.EscapeUriString(returnUrl))
                        };
                        IAuthenticationRequest request = Openid.CreateRequest(Request.Form["openid_identifier"], Realm.AutoDetect, uri.Uri);

                        // google openid
                        var fetch = new FetchRequest();
                        fetch.Attributes.AddRequired(WellKnownAttributes.Name.First);
                        fetch.Attributes.AddRequired(WellKnownAttributes.Name.Last);
                        fetch.Attributes.AddRequired(WellKnownAttributes.Name.FullName);
                        fetch.Attributes.AddRequired(WellKnownAttributes.Contact.Email);
                        fetch.Attributes.AddRequired(WellKnownAttributes.Contact.Web.Blog);
                        fetch.Attributes.AddRequired(WellKnownAttributes.Contact.Web.Homepage);
                        request.AddExtension(fetch);

                        // other openid
                        var claims = new ClaimsRequest();
                        claims.FullName = DemandLevel.Require;
                        claims.Email = DemandLevel.Require;
                        request.AddExtension(claims);

                        //request openid_identifier
                        return request.RedirectingResponse.AsActionResult();
                    }
                    catch (ProtocolException ex)
                    {
                        // TODO handle error message in view
                        TempData["statusMessage"] = ex.Message;
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    // TODO handle error message in view
                    TempData["statusMessage"] = "Invalid identifier";
                    return Redirect(returnUrl);
                }
            }
            else
            {
                //check the response status
                switch (response.Status)
                {
                    //success status
                    case AuthenticationStatus.Authenticated:

                        string name=null, email=null, url=null;
                        
                        var claims = response.GetExtension<ClaimsResponse>();
                        if (claims != null)
                        {
                            name = claims.FullName;
                            email = claims.Email;
                        }
                        
                        var fetch = response.GetExtension<FetchResponse>();
                        if (fetch != null)
                        {
                            name = fetch.GetAttributeValue(WellKnownAttributes.Name.FullName) ??
                                string.Format("{0} {1}", fetch.GetAttributeValue(WellKnownAttributes.Name.First), fetch.GetAttributeValue(WellKnownAttributes.Name.Last));
                            email = fetch.GetAttributeValue(WellKnownAttributes.Contact.Email);
                            url = fetch.GetAttributeValue(WellKnownAttributes.Contact.Web.Homepage) ?? fetch.GetAttributeValue(WellKnownAttributes.Contact.Web.Blog);
                        }
                        
                        CommenterCookieManager.SetCommenterCookieValue(Response, email);
                        var commenter = DbContext.Commenters.SingleOrDefault(c => c.Email == email);
                        if (commenter == null)
                        {
                            DbContext.Commenters.Add(new Commenter
                            {
                                OpenId = response.ClaimedIdentifier.ToString(),
                                Email = email,
                                Name = name,
                                Url = url
                            });
                        }
                        else
                        {
                            commenter.OpenId = commenter.OpenId ?? response.ClaimedIdentifier.ToString();
                        }
                        DbContext.SaveChanges();

                        return Redirect(returnUrl);

                    case AuthenticationStatus.Canceled:
                        // TODO handle error message in view
                        TempData["statusMessage"] = "Canceled at provider";
                        return Redirect(returnUrl);

                    case AuthenticationStatus.Failed:
                        // TODO handle error message in view
                        TempData["statusMessage"] = response.Exception.Message;
                        return Redirect(returnUrl);
                }
            }
            return new EmptyResult();
        }

    }
}

MyStory/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStory.Helpers;
using MyStory.ViewModels;
using MyStory.QueryObjects;
using AutoMapper;
using MyStory.Models;

namespace MyStory.Controllers
{
    public class TagController : MyStoryController
    {
        public ActionResult Search()
        {
            var term = Request.Params["term"].ToString();

            // TODO 
            // This is dilema, that is, L2E does not translate custom expression, we cannot use Contains() extension method
            // That means we need to convert TagText to upper case or lower cas to compare case insensitive in query level,
            // we know, this will cause performance problem
            // So, instead I just select everything then filtered in Linq To Object level
            // But, This altanative also causes performance problem
            // I need to find more elegance way to solve this issue.

            // #1
            var tags = DbContext.Tags.Where(t => t.TagText.ToUpper().Contains(term.ToUpper())).Select(t => t.TagText).ToList();
            
            // #2
            //var allTags = dbContext.Tags.ToList();
            //var tags = allTags.Where(t => t.TagText.Contains(term, StringComparison.OrdinalIgnoreCase)).Select(t=>t.TagText).ToList();

            if (Request.IsAjaxRequest())
            {
                return Json(tags, JsonRequestBehavior.AllowGet);
            }

            return View("Search", tags);
        }

        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            var tags = from t in DbContext.Tags
                       where t.Posts.Count > 0
                       orderby t.Posts.Count descending
                       select new TagSidebarViewModel
                       {
                           Id = t.Id,
                           TagText = t.TagText,
                           Count = t.Posts.Count
                       };

            return View("Sidebar", tags.ToList());
        }

        public ActionResult Index(string tag=null, int page=1)
        {
            ViewBag.TagText = tag;

            int perPage = page == 1 ? 20 : 10;

            var posts = new PostQuery() 
                        {
                            CurrentPageNumber = page, 
                            PostsPerPage = perPage, 
                            Tag=tag 
                        }
                        .GetQuery(DbContext)
                        .ToList();

            var postListViewModel = Mapper.Map<List<Post>, List<PostListViewModel>>(posts);

            return View("Index", postListViewModel);
        }

    }
}

MyStory/Views/Post/DeletePostPopupPartial.cshtml
<div class="modal hide fade" id="modal-delete-post">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>
            MyStory</h3>
    </div>
    <div class="modal-body">
        <p>
            Delete Post?</p>
    </div>
    <div class="modal-footer">
        <a id="delete-confirm" href="#" class="btn btn-primary">Delete</a> <a href="#" class="btn"
            data-dismiss="modal">Close</a>
    </div>
</div>

MyStory/Views/Post/Detail.cshtml
@model MyStory.ViewModels.PostDetailViewModel
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.CurrentUrl = Url.Action("Detail", "Post", new { Id = Model.Id }, "http");   // by specifying protocol in the last parameter, you will get absolute url instead of relative url
}
@section Style{
    <link href="@Url.Content("~/Content/Prettify/Themes/sons-of-obsidian.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/openid-selector/openid.css")" rel="stylesheet" type="text/css" />
}
<p>
    <h2 class="article-title">@Html.DisplayFor(model => model.Title)</h2>
</p>
<div>
    @Html.Raw(Model.Content)
</div>
<div style="margin-top: 30px">
    <p>
        @Facebook.LikeButton(href:@Request.Url.AbsoluteUri, buttonLayout:"button_count", showFaces:false, width:650, height:20)
    </p>
    <p>
        <i class="icon-share"></i> <b>Share with</b> @LinkShare.GetHtml(Model.Title, linkSites: new LinkShareSite[] { LinkShareSite.Twitter, LinkShareSite.Facebook, LinkShareSite.Digg,LinkShareSite.Reddit, LinkShareSite.StumbleUpon })
    </p>
    <p>
        <i class="icon-time"></i> <b>Posted at @Html.DisplayFor(model => model.DateCreated)</b>
    </p>
    <div>
        @if (Model.Tags != null && Model.Tags.Count() > 0)
        {
            <i class="icon-tags"></i>
        }
        @foreach (var item in Model.Tags)
        {
            <a href="@Url.Action("Index", "Tag", new { tag = @item })" class="btn btn-info btn-mini">@item</a>
        }
    </div>
    <div class="btn-group" style="margin-top: 10px; margin-bottom: 20px">
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink("Edit", "Edit", "Post", new { id = Model.Id }, new { @class = "btn" })
            <a  class="btn" data-toggle="modal" href="#modal-delete-post" onclick="openModal('@Model.Id');" >
                Delete</a>
            @Html.ActionLink("Back to List", "Index", "Home", null, new { @class = "btn" })
        }
    </div>
    
    @Html.Action("PostCommentsList", "Comment", new { PostId = Model.Id })

    <div class="well shadow">
    <div>
        <form action="@Url.Action("Authenticate", "OpenId")" method="post" id="openid_form">
        <label for="openid_identifier"><strong><i class="icon-user"></i> You can use your OpenID provider. <a href="http://openid.net/" target="_blank"">OpenID?</a></strong></label>
        <div id="openid_btns" ></div>
        <div id="openid_input_area">
            <input id="openid_identifier" name="openid_identifier" type="text" value="http://" />
            <input type="submit" value="Login" />
        </div>
        <input type="hidden" name="returnUrl" value="@ViewBag.CurrentUrl" />
        </form>    
    </div>
    <div>
        @using (Html.BeginForm("Write", "Comment", FormMethod.Post))
        {   
            @Html.ValidationSummary(true, "Post comment was unsuccessful. Please correct the errors and try again.", new { @class = "alert alert-error" })

            <div>
                @Html.TextBoxFor(model => model.CommentInput.Name, new { placeholder = "Name" })
                @Html.ValidationMessageFor(model => model.CommentInput.Name)
            </div>

            <div>
                @Html.TextBoxFor(model => model.CommentInput.Email, new { placeholder = "Email" })
                @Html.ValidationMessageFor(model => model.CommentInput.Email)
            </div>

            <div>
                @Html.TextBoxFor(model => model.CommentInput.Url, new { placeholder = "Url" })
                @Html.ValidationMessageFor(model => model.CommentInput.Url)
            </div>

            <div>
                @Html.TextAreaFor(model => model.CommentInput.Content, new { style = "WIDTH:98%;Height:250px", placeholder="Comment" })
                @Html.ValidationMessageFor(model => model.CommentInput.Content)
            </div>
            
            @Html.HiddenFor(model=>model.Id)
            @Html.HiddenFor(model=> model.CommentInput.OpenId)
            <div class="form-actions">
                <input type="submit" value="Post Comment" class="btn btn-primary" />
            </div>
        }
    </div>
    </div>
    

    @* Comments using facebook account
    @{
        Facebook.Initialize(ViewBag.FaceBookAppId, ViewBag.FaceBookAppSecret);
    }
    @Facebook.GetInitializationScripts()
    @Facebook.Comments(xid:@Html.Encode(@Request.Url.AbsoluteUri))*@
</div>


@Html.Partial("~/Views/Post/DeletePostPopupPartial.cshtml")
@section Script
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/openid-selector/openid-jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/openid-selector/openid-en.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            // remove container box 
            $('#main-body').removeClass('well');
            $('#main-body').removeClass('shadow');

            openid.init('openid_identifier');

            $('pre').addClass('prettyprint linenums');
            prettyPrint();

            $('#delete-confirm').click(function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    async: false,
                    url: "/Post/Delete/" + selectedPostIdToDelete,
                    contentType: "application/json",
                    dataType: "json",
                    success: function (result) {
                        location.href = "/Home/Index";
                    },
                    error: function (request, status, error) {
                        alert(error);
                    }
                });
            });
        });

        var selectedPostIdToDelete;

        function openModal(postId) {
            this.selectedPostIdToDelete = postId;
        }
    </script>
}

MyStory/Views/Post/Edit.cshtml
@model MyStory.ViewModels.PostInput
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Style{
<link href="@Url.Content("~/Scripts/mdd_styles.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <style>
        .ui-autocomplete-loading
        {
            background: white url('/Content/images/ui-anim_basic_16x16.gif') right center no-repeat;
        }
    </style>
}
<h2 class="page-header">
    Edit</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Latitude)
    @Html.HiddenFor(model => model.Longitude)
    
    <div>
        @Html.TextBoxFor(model => model.Title, new { @class = "input-xlarge", style = "width:100%", placeholder = "Title" })
        @Html.ValidationMessageFor(model => model.Title)
    </div>
    
    <div class="mdd_toolbar">
    </div>
    
    @Html.TextArea("Content", new { @class = "mdd_editor", rows = 15 })
    
    <div class="mdd_resizer">
    </div>
    
    @Html.ValidationMessageFor(model => model.Content)
    
    <div style="margin-top: 10px">
        @Html.TextBoxFor(model => model.Tags, new { style = "width:100%", @class = "input-xlarge", placeholder = "Tag" })
    </div>
    
    <div class="form-actions" align="center">
        <input type="submit" value="Save" class="btn btn-primary btn-large" />
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-inverse btn-large" })
    </div>
        
    <div class="mdd_preview">
    </div>
}
@section Script
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/MarkdownDeepLib.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.18.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/mystory.tag.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $("textarea.mdd_editor").MarkdownDeep({
                help_location: "/Scripts/mdd_help.htm",
                ExtraMode: true
            });
        })
    </script>
}

MyStory/Views/Post/PostListSummaryViewPartial.cshtml
@model IEnumerable<MyStory.ViewModels.PostListViewModel>

<div id="masonry-container">
    @if (Model != null)
    {
        foreach (var item in Model)
        {
        <div class="masonrybox shadow" style="padding:5px" id="@item.Id">
            <h3>
                @Html.ActionLink(item.TitleShort, "Detail", "Post", new { Id = item.Id }, new { @class = "article-title", title = item.Title, name = item.Id })</h3>
            <p>
                @Html.Raw(item.Content)</p>
            @if (Request.IsAuthenticated)
            {
                <p>
                    @Html.ActionLink("edit", "Edit", "Post", new { id = item.Id }, null) | <a  class="delete-post-link" data-toggle="modal" href="#modal-delete-post" onclick="openModal('@item.Id');" >
                        delete</a>
                </p>
            }
        </div>
        }
    }
</div>

@* view using Bootstrap Thumbnail *@ @*<ul class="thumbnails">
    @if (Model != null)
    {
        foreach (var item in Model)
        {
        <li class="span3">            
            <div class="thumbnail shadow">
            <h3>
                @Html.ActionLink(item.Title, "Detail", "Post", new { Id = item.Id }, new { @class = "article-title" })</h3>
            <p>
                @Html.Raw(item.Content)
            </p>
            @if (Request.IsAuthenticated)
            {
                <p>
                    @Html.ActionLink("edit", "Edit", "Post", new { id = item.Id }, null) | <a  class="delete-post-link" data-toggle="modal" href="#modal-delete-post" onclick="openModal('@item.Id');" >
                        delete</a>
                </p>
            }
            </div>
        </li>
        }
    }
</ul>*@



<nav id="page-nav">
@if (ViewData["url"] != null)
{
    <a href="@ViewData["url"]?page=2"></a>  
}
else
{
    <a href="/home/index?page=2"></a>
}
</nav>

MyStory/Views/Post/PostsListStylePartial.cshtml
<link href="@Url.Content("~/Content/Prettify/Themes/sons-of-obsidian.css")" rel="stylesheet" type="text/css" />

MyStory/Views/Post/PostsListSummaryViewScriptPartial.cshtml
<script src="@Url.Content("~/Scripts/jquery.masonry.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.infinitescroll.min.js")" type="text/javascript"></script>
<script type="text/javascript">
        $(function () {
             $('pre').addClass('prettyprint linenums');
            prettyPrint();

            $('.article-title').tooltip({
                placement: 'top',
                delay: { show: 200, hide: 100 },
            });

            var $container = $('#masonry-container');

            $container.masonry({
                itemSelector: '.masonrybox',
                isAnimated: true
            });

            $container.infinitescroll({
              navSelector  : '#page-nav',    // selector for the paged navigation 
              nextSelector : '#page-nav a',  // selector for the NEXT link (to page 2)
              itemSelector : '.masonrybox',     // selector for all items you'll retrieve
              loadingText : 'Loading new posts...',
              },
              // trigger Masonry as a callback
              function( newElements ) {
                // hide new items while they are loading
                var $newElems = $( newElements ).css({ opacity: 0 });
                // ensure that images load before adding to masonry layout
                $newElems.imagesLoaded(function(){
                  // show elems now they're ready
                  $newElems.animate({ opacity: 1 });
                  $container.masonry( 'appended', $newElems, true ); 
                });
              }
            );

            $('#delete-confirm').click(function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    async: false,
                    url: "/Post/Delete/" + selectedPostIdToDelete,
                    contentType: "application/json",
                    dataType: "json",
                    success: function (result) {
                        $('#modal-delete-post').modal('hide');  // hide modal
                        $('div#' + selectedPostIdToDelete).remove();            // remove the deleted article
                        $container.masonry('reload'); //.reload(); // reload masonry layout
                    },
                    error: function (request, status, error) {
                        alert(error);
                    }
                });
            });
        });

        var selectedPostIdToDelete;

        function openModal(postId) {
            this.selectedPostIdToDelete = postId;
        }
</script>

MyStory/Views/Post/Write.cshtml
@model MyStory.ViewModels.PostInput
@{
    ViewBag.Title = "Write";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Style{
    <link href="@Url.Content("~/Scripts/mdd_styles.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <style>
        .ui-autocomplete-loading
        {
            background: white url('/Content/images/ui-anim_basic_16x16.gif') right center no-repeat;
        }
    </style>
}
<h2 class="page-header">
    Posting</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div>
        @Html.TextBoxFor(model => model.Title, new { @class = "input-xlarge", style = "width:100%", placeholder = "Title", autofocus="autofocus" })
        @Html.ValidationMessageFor(model => model.Title)
    </div>
    
    <div class="mdd_toolbar">
    </div>
    
    @Html.TextArea("Content", new { @class = "mdd_editor", rows = 15 })
    
    <div class="mdd_resizer">
    </div>
    
    @Html.ValidationMessageFor(model => model.Content)

    <div style="margin-top: 10px">
        @Html.TextBoxFor(model => model.Tags, new { style = "width:100%", @class = "input-xlarge", placeholder = "Tag, Use comma delimiter for multiple tags" })
    </div>
    
    <div class="form-actions" align="center">
        <input type="submit" value="Save" class="btn btn-primary btn-large" />
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-inverse btn-large" })
    </div>
        
    <div class="mdd_preview">
    </div>
}
@section Script
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/MarkdownDeepLib.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.18.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/mystory.tag.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('#new-post-nav').addClass('active');

            $("textarea.mdd_editor").MarkdownDeep({
                help_location: "/Scripts/mdd_help.htm",
                ExtraMode: true
            });
        })
    </script>
}